name: "ci"

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    timeout-minutes: 15
    runs-on: "ubuntu-latest"
    env:
      CI: "1"
      TZ: "Europe/Paris"
      DO_NOT_TRACK: "1"
    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1

      - name: "Setup Node.js"
        uses: "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020" # v7.0.0
        with:
          node-version: "24.16.0"
          cache: "npm"
      - run: "node --version"

      - run: "npm clean-install"
      # - run: "node --run lint:typescript" # already covered by oxlint
      - run: "node --run lint:oxlint"
      - run: "node --run lint:oxfmt"
      - run: "node --run test"
      - run: "node --run build"
